### ISSUE TITLE
base64 error

### ISSUE THREAD

**Issue by losisin** [elgohr/gcloud-login-action#3]
I've added the contents of gcloud service account json file as secret in my repository. However, when this action runs it fails with the following error:
```sh
base64: invalid input
##[error]Docker run failed with exit code 1
```
Here is my workflow yaml
```yaml
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v1
      - name: login to registry
        id: gcloud
        uses: elgohr/gcloud-login-action@master
        with:
          account_key: ${{ secrets.DOCKER_PASSWORD }}
```
I also tried encoding the json file and adding that as secret, but then `login to registry` step fails with:
```sh
ERROR: (gcloud.auth.activate-service-account) Could not read json file /github/home/gcloud.json: No JSON object could be decoded
##[error]Docker run failed with exit code 1
```

Any help would greatly appreciated
